namespace MyLibrary
{
    [default_interface]
    runtimeclass Class
    {
        Class();
        Int32 MyProperty;
        static Windows.Foundation.IAsyncAction WasteTimeAsync(Windows.Foundation.TimeSpan howLong);
    }
}
